package com.kline.inventorypos.feature.report
import androidx.compose.foundation.background
import androidx.compose.foundation.horizontalScroll
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.lazy.*
import androidx.compose.foundation.rememberScrollState
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.automirrored.outlined.TrendingUp
import androidx.compose.material.icons.outlined.*
import androidx.compose.material3.*
import androidx.compose.runtime.Composable
import androidx.compose.ui.*
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
import com.kline.inventorypos.core.common.formatUgx
import com.kline.inventorypos.core.designsystem.*
import com.kline.inventorypos.core.model.*
import java.util.Locale

@Composable fun ManagementReportScreen(state:ManagementReportUiState,onBack:()->Unit,onPeriod:(ReportPeriod)->Unit,onRefresh:()->Unit){Column(Modifier.fillMaxSize().background(MaterialTheme.colorScheme.background)){FocusedHeader("Management reports","Sales, profitability and cash flow",onBack);LazyColumn(Modifier.weight(1f),contentPadding=PaddingValues(12.dp),verticalArrangement=Arrangement.spacedBy(10.dp)){item{Row(Modifier.fillMaxWidth().horizontalScroll(rememberScrollState()),horizontalArrangement=Arrangement.spacedBy(7.dp)){ReportPeriod.entries.forEach{p->FilterChip(state.period==p,{onPeriod(p)},{Text(p.label)})}}};if(state.loading&&state.workspace.sales==null&&state.workspace.financial==null)item{Box(Modifier.fillMaxWidth().height(180.dp),contentAlignment=Alignment.Center){CircularProgressIndicator()}};state.workspace.sales?.let{s->item{SalesCard(s)};if(s.daily.isNotEmpty())item{TrendCard(s.daily)}};state.workspace.financial?.let{f->item{ProfitCard(f)};item{CashFlowCard(f)};if(f.expenseCategories.isNotEmpty())item{ExpenseBreakdown(f.expenseCategories)}};if(!state.loading&&state.workspace.sales==null&&state.workspace.financial==null)item{Surface(Modifier.fillMaxWidth(),shape=RoundedCornerShape(12.dp)){Text("No report permission is available for this account.",Modifier.padding(20.dp),color=Slate500)}}};Surface(shadowElevation=6.dp){OutlinedButton(onRefresh,Modifier.fillMaxWidth().padding(12.dp),enabled=!state.loading){Icon(Icons.Outlined.Refresh,null);Text("  Refresh reports")}}}}
@Composable private fun SalesCard(s:SalesPeriodReport){PosCard(Modifier.fillMaxWidth()){Column(Modifier.padding(14.dp),verticalArrangement=Arrangement.spacedBy(8.dp)){Title("Sales performance",Icons.Outlined.Assessment);Text(formatUgx(s.netRevenue),style=MaterialTheme.typography.headlineMedium,fontFamily=MoneyFontFamily,fontWeight=FontWeight.Bold);Text("Net revenue · ${s.transactions} transactions · ${s.uniqueCustomers} customers",color=Slate500);Row(horizontalArrangement=Arrangement.spacedBy(8.dp)){Metric("Gross",s.grossRevenue,Modifier.weight(1f));Metric("Average",s.averageSale,Modifier.weight(1f))};MoneyRow("Returns",s.returns);MoneyRow("Discounts",s.discounts);MoneyRow("Tax",s.tax)}}}
@Composable private fun ProfitCard(f:FinancialReport){PosCard(Modifier.fillMaxWidth()){Column(Modifier.padding(14.dp),verticalArrangement=Arrangement.spacedBy(8.dp)){Title("Profitability",Icons.AutoMirrored.Outlined.TrendingUp);MoneyRow("Net revenue",f.revenue);MoneyRow("Cost of goods",f.cogs);MoneyRow("Gross profit",f.grossProfit);PercentRow("Gross margin",f.grossMargin);MoneyRow("Operating expenses",f.expenses);MoneyRow("Net profit",f.netProfit);PercentRow("Net margin",f.netMargin)}}}
@Composable private fun CashFlowCard(f:FinancialReport){PosCard(Modifier.fillMaxWidth()){Column(Modifier.padding(14.dp),verticalArrangement=Arrangement.spacedBy(8.dp)){Title("Cash flow",Icons.Outlined.AccountBalance);MoneyRow("Inflows",f.cashInflows);MoneyRow("Outflows",f.cashOutflows);Surface(Modifier.fillMaxWidth(),color=if(f.netCashFlow>=0)MoneyGreen50 else Error50,shape=RoundedCornerShape(10.dp)){Row(Modifier.padding(12.dp)){Text("Net cash flow",Modifier.weight(1f),fontWeight=FontWeight.Bold);Text(formatUgx(f.netCashFlow),fontFamily=MoneyFontFamily,fontWeight=FontWeight.Bold,color=if(f.netCashFlow>=0)MoneyGreen700 else Error700)}}}}}
@Composable private fun TrendCard(days:List<SalesDay>){PosCard(Modifier.fillMaxWidth()){Column(Modifier.padding(14.dp),verticalArrangement=Arrangement.spacedBy(7.dp)){Text("Daily sales",fontWeight=FontWeight.Bold);days.takeLast(14).reversed().forEach{d->Row(Modifier.fillMaxWidth()){Text(d.date,Modifier.weight(1f),color=Slate500);Text("${d.transactions} sales",Modifier.weight(1f),color=Slate500);Text(formatUgx(d.revenue),fontFamily=MoneyFontFamily,fontWeight=FontWeight.Bold)}}}}}
@Composable private fun ExpenseBreakdown(rows:List<ReportCategory>){PosCard(Modifier.fillMaxWidth()){Column(Modifier.padding(14.dp),verticalArrangement=Arrangement.spacedBy(7.dp)){Text("Expense categories",fontWeight=FontWeight.Bold);rows.sortedByDescending{it.total}.forEach{r->Row(Modifier.fillMaxWidth()){Text(r.name,Modifier.weight(1f));Text("${r.entries} entries",Modifier.weight(1f),color=Slate500);Text(formatUgx(r.total),fontFamily=MoneyFontFamily,fontWeight=FontWeight.Bold)}}}}}
@Composable private fun Title(text:String,icon:androidx.compose.ui.graphics.vector.ImageVector){Row(verticalAlignment=Alignment.CenterVertically){Icon(icon,null,tint=Primary700);Text("  $text",fontWeight=FontWeight.Bold)}}
@Composable private fun Metric(label:String,value:Long,modifier:Modifier){Surface(modifier,color=Primary50,shape=RoundedCornerShape(10.dp)){Column(Modifier.padding(10.dp)){Text(label,color=Primary700,style=MaterialTheme.typography.labelSmall);Text(formatUgx(value),fontFamily=MoneyFontFamily,fontWeight=FontWeight.Bold)}}}
@Composable private fun MoneyRow(label:String,value:Long){Row(Modifier.fillMaxWidth(),horizontalArrangement=Arrangement.SpaceBetween){Text(label,color=Slate500);Text(formatUgx(value),fontFamily=MoneyFontFamily,fontWeight=FontWeight.Bold)}}
@Composable private fun PercentRow(label:String,value:Double?){Row(Modifier.fillMaxWidth(),horizontalArrangement=Arrangement.SpaceBetween){Text(label,color=Slate500);Text(value?.let{String.format(Locale.US,"%.1f%%",it)}?:"—",fontWeight=FontWeight.Bold)}}
