package com.kline.inventorypos.feature.administration
import androidx.compose.foundation.background
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.lazy.*
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.outlined.*
import androidx.compose.material3.*
import androidx.compose.runtime.Composable
import androidx.compose.ui.*
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
import com.kline.inventorypos.core.designsystem.*
@Composable fun AdministrationScreen(state:AdministrationUiState,onBack:()->Unit,onRefresh:()->Unit){Column(Modifier.fillMaxSize().background(MaterialTheme.colorScheme.background)){FocusedHeader("Settings & team","Store, branch, tax, printer and people overview",onBack);LazyColumn(Modifier.weight(1f),contentPadding=PaddingValues(12.dp),verticalArrangement=Arrangement.spacedBy(10.dp)){if(state.loading&&state.workspace.store==null)item{Box(Modifier.fillMaxWidth().height(180.dp),contentAlignment=Alignment.Center){CircularProgressIndicator()}};state.workspace.store?.let{s->item{AdminCard("Store identity",Icons.Outlined.Store){RowText("Name",s.name);RowText("Address",s.address);RowText("Phone",s.phone?:"Not set");RowText("Email",s.email?:"Not set");RowText("Currency",s.currency)}};item{AdminCard("Tax & sales policy",Icons.Outlined.Policy){RowText("Tax",if(s.taxEnabled)"${s.taxLabel} enabled" else "Disabled");RowText("Registration",s.taxRegistration?:"Not set");RowText("Return window","${s.returnWindowDays} days")}};item{AdminCard("Receipt & printer",Icons.Outlined.Print){RowText("Default action",s.receiptAction?.replace('_',' ')?:"Not set");RowText("Printer bridge",s.printerBridgeUrl?:"Not configured");Text("Hardware-specific setup remains on the secured web administration console until printer models and network mode are approved.",color=Slate500,style=MaterialTheme.typography.bodySmall)}}};if(state.workspace.branches.isNotEmpty()){item{Text("Branches",fontWeight=FontWeight.Bold)};items(state.workspace.branches,key={it.id}){b->Surface(Modifier.fillMaxWidth(),color=MaterialTheme.colorScheme.surface,shape=RoundedCornerShape(12.dp)){Row(Modifier.padding(12.dp),verticalAlignment=Alignment.CenterVertically){Icon(Icons.Outlined.Storefront,null,tint=Primary700);Column(Modifier.padding(start=10.dp).weight(1f)){Text(b.name,fontWeight=FontWeight.Bold);Text("${b.code} · ${b.city?:"Location not set"}",color=Slate500)};Text(b.status,color=if(b.status=="active")MoneyGreen700 else Slate500)}}}};if(state.workspace.staff.isNotEmpty()){item{Text("Active team",fontWeight=FontWeight.Bold)};items(state.workspace.staff,key={it.id}){p->Surface(Modifier.fillMaxWidth(),color=MaterialTheme.colorScheme.surface,shape=RoundedCornerShape(12.dp)){Row(Modifier.padding(12.dp)){Icon(Icons.Outlined.Person,null,tint=Primary700);Column(Modifier.padding(start=10.dp)){Text(p.name,fontWeight=FontWeight.Bold);Text(listOfNotNull(p.position,p.employeeId,p.phone).joinToString(" · "),color=Slate500,style=MaterialTheme.typography.bodySmall)}}}}}};Surface(shadowElevation=6.dp){OutlinedButton(onRefresh,Modifier.fillMaxWidth().padding(12.dp),enabled=!state.loading){Icon(Icons.Outlined.Refresh,null);Text("  Refresh administration")}}}}
@Composable private fun AdminCard(title:String,icon:androidx.compose.ui.graphics.vector.ImageVector,content:@Composable ColumnScope.()->Unit){PosCard(Modifier.fillMaxWidth()){Column(Modifier.padding(14.dp),verticalArrangement=Arrangement.spacedBy(8.dp)){Row(verticalAlignment=Alignment.CenterVertically){Icon(icon,null,tint=Primary700);Text("  $title",fontWeight=FontWeight.Bold)};content()}}}
@Composable private fun RowText(label:String,value:String){Row(Modifier.fillMaxWidth(),horizontalArrangement=Arrangement.SpaceBetween){Text(label,color=Slate500);Text(value,fontWeight=FontWeight.Bold)}}
